import type { Metadata } from 'next'
import './globals.css'
import { notoSans, poppins } from './ui/fonts'


export const metadata: Metadata = {
  title: 'Assign actions to users and groups',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={notoSans.className}>{children}</body>
    </html>
  )
}
